c975LEmail:
    roleNeeded:
        type: string
        required: true
        default: ROLE_ADMIN
        info: "User's role needed to enable access to data linked to EmailBundle: i.e. ROLE_ADMIN (default)"
    sentFrom:
        type: string
        required: true
        default: null
        info: "Email address used to send emails: i.e. contact@example.com"
