services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\EmailBundle\Controller\:
        resource: '../../Controller/*'

    c975L\EmailBundle\Security\:
        resource: '../../Security/*'
        bind:
            $roleNeeded: '%c975_l_email.roleNeeded%'

    c975L\EmailBundle\Service\:
        resource: '../../Service/*'