services:
    _defaults:
        autowire: false
        autoconfigure: true

    c975L\EmailBundle\Controller\EmailController: ~

    c975L\EmailBundle\Security\EmailVoter:
        arguments:
            $decisionManager: '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'
            $roleNeeded: '%c975_l_email.roleNeeded%'

    c975L\EmailBundle\Service\EmailService:
        arguments:
            $em: '@Doctrine\ORM\EntityManagerInterface'
            $mailer: '@Swift_Mailer'
            $paginator: '@Knp\Component\Pager\PaginatorInterface'

    c975L\EmailBundle\Service\EmailServiceInterface: '@c975L\EmailBundle\Service\EmailService'
