services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\EmailBundle\Controller\:
        resource: '../../Controller/*'

    c975L\EmailBundle\Service\:
        resource: '../../Service/*'