services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\EmailBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\EmailBundle\Security\:
        resource: '../src/Security/*'

    c975L\EmailBundle\Service\:
        resource: '../src/Service/*'